---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 35
# Threads per worker
threads_per_worker: 1
# Start/end date/time
startdate: '20181015.0000'
enddate: '20190303.0000'
# Maximum time difference allowed to match the datasets
time_window: 300  # [second]
# Input/output file locations
# Track stats directory
stats_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1.new/stats/'
# Track pixel file directory
pixelfile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1.new/celltracking/20181015.0000_20190303.0000/'
# PPI 3D file directory
ppifile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_gridded.c1/'
# Satellite pixel file directory
satfile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corvisstpx2drectg16v4minnisX1.parallaxcorrected_regrid2csapr2gridded.c1/'
# Sounding stats file
sonde_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/sounding_stats/'
sonde_file: '/global/cscratch1/sd/feng045/iclass/cacti/arm/sounding_stats/Interpsonde_parameters_CACTI_AMF_2Oct-30Apr.nc'