---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 30
# Threads per worker
threads_per_worker: 1
# Maximum time difference allowed to match satellite data
time_window: 5  # [minutes]
# Start/End process dates
start_datetime: '2018-10-15'
end_datetime: '2019-10-31'
# Input/output file locations
convmask_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_gridded_convmask.c1/'
rain_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_composite_rain.c1/'
sat_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corvisstpx2drectg16v4minnisX1.parallaxcorrected_regrid2csapr2gridded.c1/'
out_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_convmaskmerge.c1/'
# File basenames
convmask_basename: 'taranis_corcsapr2cfrppiqcM1_convmask.c1.'
rain_basename: 'taranis_corcsapr2cfrppiqcM1_composite_rain.c1.'
sat_basename: 'corvisstpx2drectg16v4minnisX1.regrid2csapr2gridded.c1.'
out_basename: 'taranis_corcsapr2cfrppiqcM1_convmask.c1.'