---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 32
# Threads per worker
threads_per_worker: 1
# Dates to work on
dates_input: '201904'
# Satellite data directory
#dir_input: '/global/cfs/projectdirs/m1657/avarble/GOES/corvisstpx2drectg16v4minnisX1.parallaxcorrected.c1/'
dir_input: '/global/cscratch1/sd/avarble/cacti/GOES/corvisstpx2drectg16v4minnisX1.parallaxcorrected.c1/'
# Destination grid (CSAPR grid file)
file_radar: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corgridded_terrain.c0/CSAPR2_Taranis_Gridded_500m.Terrain_RangeMask.nc'
# Pre-generated weight file (produced by test_regrid_goes16_to_csapr.ipynb)
weight_file: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corvisstpx2drectg16v4minnisX1.regridweights.c1/nearest_s2d_728x672_441x441.nc'
# Output directory
dir_output: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corvisstpx2drectg16v4minnisX1.parallaxcorrected_regrid2csapr2gridded.c1/'
# Input/Output file basename
basename_input: 'corvisstpx2drectg16v4minnisX1.parallaxcorrected.c1.'
basename_output: 'corvisstpx2drectg16v4minnisX1.regrid2csapr2gridded.c1.'
