---
# Run in parallel
run_parallel: 1
# Number of workers for Dask
n_workers: 32
# Threads per worker
threads_per_worker: 1
# Start/end date/time
startdate: '20181015.0000'
enddate: '20190303.0000'
# Maximum time difference allowed to match the datasets
time_window: 300  # [second]
# Input/output file locations
# Track stats directory
stats_path: '/gpfs/wolf2/arm/atm131/proj-shared/enochjo/cacti/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1/stats/'
# stats_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1/stats/'
# Track pixel file directory
pixelfile_path: '/gpfs/wolf2/arm/atm131/proj-shared/enochjo/cacti/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1/celltracking/20181015.0000_20190303.0000/'
# pixelfile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1/celltracking/20181015.0000_20190303.0000/'
# PPI 3D file directory
ppifile_path: '/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/csapr/taranis_corcsapr2cfrppiqcM1_gridded.c1/'
# ppifile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_gridded.c1/'
# Satellite pixel file directory
satfile_path: '/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/csapr/corvisstpx2drectg16v4minnisX1.parallaxcorrected_regrid2csapr2gridded.c1/'
# satfile_path: '/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corvisstpx2drectg16v4minnisX1.parallaxcorrected_regrid2csapr2gridded.c1/'
# Sounding stats file
sonde_file: '/gpfs/wolf2/arm/atm131/proj-shared/zfeng/cacti/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1/stats/Interpsonde_parameters_CACTI_AMF_2Oct-30Apr_v3.1.1.nc'
# sonde_file: '/global/cfs/cdirs/m1657/zfeng/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1.new/stats/Interpsonde_parameters_CACTI_AMF_2Oct-30Apr_v3.1.1.nc'
# Aerosol file
aerosol_file: '/gpfs/wolf2/arm/atm131/proj-shared/enochjo/cacti/CACTI_Aerosol_Concentrations_15min.nc'
# aerosol_file: '/global/cfs/projectdirs/m1657/avarble/cacti/CACTI_Aerosol_Concentrations_15min.nc'